### ISSUE TITLE
Where to set Redirect URL.

### ISSUE THREAD

**Issue by MangeshVyas** [JimLiu/WeiboSDK#13]
I am using sample code "PublicTimelineSample" I have set redirect URL on Project setting at weibo because my Android app uses redirect URL, Now I also need to set this for iOS. How can I do this. 

Thanks.

**Comment by JimLiu** [comment]
fixed in https://github.com/JimLiu/WeiboSDK/commit/740a55f06043c29479816b1c97e46e7dbdb89b8a
