### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by JianWenXie** [JimLiu/WeiboSDK#17]
楼主,能不能不要放那么多demo 在里面,我一打开真不知道是哪一个.还有api文档总得有吧?实例程序总得有吧?我是初学者.建议楼主谢谢

**Comment by JimLiu** [comment]
使用说明都已经写在了readme。
api文档需要参考微博的API文档：
http://open.weibo.com/wiki/%E5%BE%AE%E5%8D%9AAPI
示例程序在samples目录下
